server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: customers-route
          uri: http://localhost:8091
          predicates:
            - Path=/customers/**
        - id: risk-analysis-route
          uri: http://localhost:8092
          predicates:
            - Path=/risk-analysis/**
        - id: loan-proposals-route
          uri: http://localhost:8093
          predicates:
            - Path=/loan-proposals/**

